# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5640c3d9af6734b8c4a2fe88b888d7431e261c89c857cdecea4084bc5a6885de7443798d0d82fa9a975f892ec1413680102b1defbebd38bb47038daf955caee6

test:
  secret_key_base: 5c0f989ec5e4ccc976d8b4ee3e8aab79fc3dc2d218dc63b21c16df3366ffcc03bec2392e62d6f3b869e9ee7b0b42ce9f97ab93a9790e36ecc47a72f29e79a232

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
